# Generated by Django 5.0.3 on 2024-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
