# Generated by Django 5.0.3 on 2024-04-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_enrollment_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.AddField(
            model_name='grade',
            name='enroll',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='available',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.available'),
        ),
    ]
