# Generated by Django 5.0.3 on 2024-04-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_available_remove_enrollment_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='registration_deadline',
            field=models.DateField(default=None, null=True),
        ),
    ]
