# Generated by Django 5.0.3 on 2024-04-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_available_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='back.available'),
        ),
    ]
